# Problem 1: Generating a Vandermonde Matrix

In [1]:
import numpy as np

In [2]:
def vandermonde(input_vector, increasing=False):
    n = len(input_vector)
    if increasing:
        return np.column_stack([input_vector ** i for i in range(n)])
    else:
        return np.column_stack([input_vector ** (n - i - 1) for i in range(n)])

In [3]:
input_vector = np.array([1, 2, 3, 4, 5])
print("Vandermonde matrix with increasing powers:")
print(vandermonde(input_vector, increasing=True))
print("\nVandermonde matrix with decreasing powers:")
print(vandermonde(input_vector, increasing=False))

Vandermonde matrix with increasing powers:
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]

Vandermonde matrix with decreasing powers:
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


# Problem 2: Moving Average Function

In [4]:
def moving_average(sequence, k):
    n = len(sequence)
    moving_averages = []
    for i in range(n - k + 1):
        window = sequence[i : i + k]
        avg = sum(window) / k
        moving_averages.append(avg)
    return moving_averages

In [5]:
sequence = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size = 3
print("Moving averages:", moving_average(sequence, window_size))

Moving averages: [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
